# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profiles', '0005_auto_20160927_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('text', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiles.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
