# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0005_auto_20160927_2022'),
        ('Entries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=1024)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiles.User')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entries.Post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
