# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entries', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_of_comments',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
