# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_auto_20160927_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
